=== indahrahma/Tugas-3-Praktikum-/tugaswebservice.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="Bidang">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element ref="alamatpenerima"/>
                <xs:element ref="alamatpengirim"/>
                <xs:element ref="email"/>
                <xs:element ref="harga"/>
                <xs:element ref="jeniskelamin"/>
                <xs:element ref="jenispengiriman"/>
                <xs:element ref="kode"/>
                <xs:element ref="kontak"/>
                <xs:element ref="nama"/>
                <xs:element ref="tanggal"/>
            </xs:choice>
            <xs:attribute name="jasa" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="alamatpenerima">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="alamat"/>
            </xs:sequence>
            <xs:attribute name="nama" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="alamat" type="xs:string"/>
    <xs:element name="alamatpengirim">
        <xs:complexType>
            <xs:attribute name="nama" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="email" type="xs:string"/>
    <xs:element name="harga" type="xs:string"/>
    <xs:element name="jeniskelamin" type="xs:NCName"/>
    <xs:element name="jenispengiriman" type="xs:NCName"/>
    <xs:element name="kode" type="xs:integer"/>
    <xs:element name="kontak" type="xs:integer"/>
    <xs:element name="nama" type="xs:string"/>
    <xs:element name="tanggal" type="xs:NMTOKEN"/>
</xs:schema>

=== indahrahma/Tugas-3-Praktikum-/tugaswebservice.xml
<?xml version="1.0" encoding="UTF-8"?>
<Bidang jasa="POS" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="tugaswebservice.xsd">
	<nama>Indah Rahmawati</nama>
	<kode>1</kode>
	<tanggal>01-04-2017</tanggal>
	<jenispengiriman>yes</jenispengiriman>
	<harga>RP: 300000</harga>
	<jeniskelamin>perempuan</jeniskelamin>
	<email>indahrahmawati6039@gmail.com</email>
	<kontak>0856789508639</kontak>
	<alamatpengirim nama="Surabaya"></alamatpengirim>
	<alamatpenerima nama="Palembang">
		<alamat>jl. sultan mahmudbadaruddin no.39</alamat>
	</alamatpenerima>
	
	<nama>Hanna Tasya</nama>
	<kode>2</kode>
	<tanggal>09-04-2017</tanggal>
	<jenispengiriman>ok</jenispengiriman>
	<harga>RP: 500000</harga>
	<jeniskelamin>Perempuan</jeniskelamin>
	<email>hannaat@gmail.com</email>
	<kontak>081289314565</kontak>
	<alamatpengirim nama="Bandung"></alamatpengirim>
	<alamatpenerima nama="Jakarta">
		<alamat>jl. Mohammad Yamin no.12</alamat>
	</alamatpenerima>
	
	<nama>Rafikatul Hikma</nama>
	<kode>3</kode>
	<tanggal>16-04-2017</tanggal>
	<jenispengiriman>ok</jenispengiriman>
	<harga>RP: 700000</harga>
	<jeniskelamin>Perempuan</jeniskelamin>
	<email>rafikatulhikma07@gmail.com</email>
	<kontak>082345459091</kontak>
	<alamatpengirim nama="Makassar"></alamatpengirim>
	<alamatpenerima nama="Bandung">
	<alamat>jl. Panjaitan no.15</alamat>
	</alamatpenerima>
	
	<nama>Tiara Riski Wulansari</nama>
	<kode>4</kode>
	<tanggal>27-04-2017</tanggal>
	<jenispengiriman>yes</jenispengiriman>
	<harga>RP: 900000</harga>
	<jeniskelamin>perempuan</jeniskelamin>
	<email>aratiaraw@gmail.com</email>
	<kontak>081255345170</kontak>
	<alamatpengirim nama="Jakarta"></alamatpengirim>
	<alamatpenerima nama="Yogyakarta">
		<alamat>jl. Rambutan no.19</alamat>
	</alamatpenerima>
	
	<nama>Diana Satima Gistivani</nama>
	<kode>5</kode>
	<tanggal>30-04-2017</tanggal>
	<jenispengiriman>yes</jenispengiriman>
	<harga>RP: 1000000</harga>
	<jeniskelamin>perempuan</jeniskelamin>
	<email>dianasatimaa@gmail.com</email>
	<kontak>0857895430991</kontak>
	<alamatpengirim nama="Pangandaran"></alamatpengirim>
	<alamatpenerima nama="Bogor">
		<alamat>jl. Kartini no.01</alamat>
   </alamatpenerima>
</Bidang>
